name: Compilador APK Android Definitivo
on:
  push:
    branches: [ principal ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compilar con Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir:.
          command: buildozer android debug
          buildozer_version: stable
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: salon-apk
          path: bin/*.apk
